---
apiVersion: v1
kind: Service
metadata:
  name: hs-debaiter-database
spec:
  selector:
    {{- include "hs-debaiter.database.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hs-debaiter-database
spec:
  selector:
    matchLabels:
      {{- include "hs-debaiter.database.selectorLabels" . | nindent 6 }}
  serviceName: hs-debaiter-database
  template:
    metadata:
      labels:
        {{- include "hs-debaiter.database.labels" . | nindent 8 }}
    spec:
      containers:
        - name: hs-debaiter-database
          image: mariadb:11.4.2
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: hs_debaiter
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hs-debaiter-database-secret
                  key: DB_PASS
          volumeMounts:
            - name: hs-debaiter-database-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: hs-debaiter-database-data
      spec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
